### ISSUE TITLE
Hope you're having a great day

### ISSUE THREAD

**Issue by kitze** [RIP21/import-move-codemod#1]
just trying something, chill

**Comment by RIP21** [comment]
LOL :D

**Comment by kitze** [comment]
@RIP21 can you close this so i can try something?

**Comment by RIP21** [comment]
Sure

**Comment by RIP21** [comment]
:dagger:

**Comment by kitze** [comment]
LOL STILL CAN COMMENT

**Comment by kitze** [comment]
is there an option to lock something so users cannot comment anymore?

**Comment by RIP21** [comment]
And now you suck! @kitze :D

**Comment by RIP21** [comment]
And now you're good to comment again @kitze

**Comment by kitze** [comment]
@RIP21 can you please unlock? I'm really testing some features :D

**Comment by kitze** [comment]
So it doesn't automatically open after unlocking it, cool

**Comment by kitze** [comment]
So when an owner closes an issue, the user cannot reopen?

**Comment by RIP21** [comment]
Yes, I think so.
